### ISSUE TITLE
scripts seems to be missing

### ISSUE THREAD

**Issue by sanguisangui** [rajibd2k/GW_beamformer#1]
2. Run CCA_NyquistDesign_script.m, CCA_Design_script.m

3. Run CCA_Windows_script_2c.m

In the readme, these scripts are descibed, but they are missing such that I do not find them in this open sources

**Comment by rajibd2k** [comment]
Sorry, it seems to be a mistake from my end. Kindly check now.

**Comment by rajibd2k** [comment]
If everything is fine, kindly close the issue as well. Thanks !

**Comment by sanguisangui** [comment]
thanks for your swift response
