### ISSUE TITLE
error of missing one function 

### ISSUE THREAD

**Issue by sanguisangui** [rajibd2k/GW_beamformer#2]
When I run the script of ' CCA_Design_script.m', the function of 'Optimized_Sensor_Positions_CCA' seems to be missing. I try to find it, but I do not get it

**Comment by rajibd2k** [comment]
I have added it now... Please check once again if the script is running properly. Please do close the issue if everything is working.

**Comment by sanguisangui** [comment]
Thanks ， now they are running well
